### ISSUE TITLE
first run on a fresh db fails

### ISSUE THREAD

**Issue by ujinjinjin** [Ujinjinjin/dingo#38]
Error | 2021-04-25 16:23:06 | Dingo.Core.Operations.MigrationOperations | MigrationOperations:RunMigrationsAsync:Error;

System.NotSupportedException: The CLR array type Dingo.Core.Repository.DbClasses.DbMigrationInfoInput[] isn't supported by Npgsql or your PostgreSQL. If you wish to map it to an  PostgreSQL composite type array you need to register it before usage, please refer to the documentation.
   at Npgsql.TypeMapping.ConnectorTypeMapper.GetByClrType(Type type)
   at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.CommandInfo.Query[T]()
   at Dingo.Core.Utils.Db.DataConnectionBase.Query[T](DbRequest request) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Utils/Db/DataConnectionBase.cs:line 155
   at Dingo.Core.Utils.Db.DataConnectionBase.Query[T](String sql, CommandType commandType, Boolean logEnabled, DataParameter[] parameters) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Utils/Db/DataConnectionBase.cs:line 137
   at Dingo.Core.Utils.Db.DataConnectionBase.Query[T](String sql, CommandType commandType, DataParameter[] parameters) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Utils/Db/DataConnectionBase.cs:line 131
   at Dingo.Core.Utils.Db.DataConnectionBase.Query[T](String sql, DataParameter[] parameters) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Utils/Db/DataConnectionBase.cs:line 113
   at Dingo.Core.Utils.Db.DataConnectionBase.QueryAsync[T](String sql, DataParameter[] parameters) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Utils/Db/DataConnectionBase.cs:line 119
   at Dingo.Core.Repository.DatabaseContext.GetMigrationsStatusAsync(IList`1 dbMigrationInfoInputList) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Repository/DatabaseContext.cs:line 52
   at Dingo.Core.Repository.DatabaseRepository.GetMigrationsStatusAsync(IList`1 migrationInfoList) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Repository/DatabaseRepository.cs:line 85
   at Dingo.Core.Operations.MigrationOperations.ReadAndApplyMigrationList(IList`1 migrationInfoList, Boolean silent, Boolean isProject) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Operations/MigrationOperations.cs:line 238
   at Dingo.Core.Operations.MigrationOperations.RunProjectMigrationsAsync(String migrationsRootPath, Boolean silent) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Operations/MigrationOperations.cs:line 184
   at Dingo.Core.Operations.MigrationOperations.RunMigrationsAsync(String migrationsRootPath, String configPath, Boolean silent, String connectionString, String providerName, String migrationSchema, String migrationTable) in /mnt/d/gallk/work/utils/dingo/Src/Dingo.Core/Operations/MigrationOperations.cs:line 133

**Comment by ujinjinjin** [comment]
For some reason npgslq isn't able to map CLR type to Postgres when it's just created, but on application rerun it works just fine

**Comment by ujinjinjin** [comment]
The reason was is that after opening connection for the first time, npgsql would cache types retrieved from database, so, when recently applied types were used, npgsql would look for it in the outdated cache. To fix this issue, I added cache clearing after applying system migrations for the first time

**Comment by ujinjinjin** [comment]
seems to be fixed
