### ISSUE TITLE
Some parameters names are mismatch in controllers and operations

### ISSUE THREAD

**Issue by ujinjinjin** [Ujinjinjin/dingo#40]
Seems like due to parameter name mismatch there is an error:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.IO.Directory.CreateDirectory(String path)
   at Dingo.Core.Adapters.DirectoryAdapter.CreateDirectory(String path) in /home/vsts/work/1/s/Src/Dingo.Core/Adapters/DirectoryAdapter.cs:line 12
   at Dingo.Core.Operations.MigrationOperations.CreateMigrationFileAsync(String name, String path) in /home/vsts/work/1/s/Src/Dingo.Core/Operations/MigrationOperations.cs:line 62
```

**Comment by ujinjinjin** [comment]
done
